### PR TITLE
Pakize

### PR DESCRIPTION
**Pull request by Nikolov87**

### CODE REVIEW

**Review by PakizeBozkurt — APPROVED** [review]
:+1:

**Review by Mujtabacyf — APPROVED** [review]
codes are fine

**Review by PakizeBozkurt — APPROVED** [review]
Okay!

**Review by FatemRahimi — APPROVED** [review]

**Comment by 12shussein** [comment]
Nice work pakize

**Review by Mujtabacyf — COMMENTED** [review]
Good

**Review by PakizeBozkurt — COMMENTED** [review]
:+1:

**Review by FatemRahimi — COMMENTED** [review]
Thank you

**Review by FatemRahimi — COMMENTED** [review]
submit

**Pull request merged**
